### ISSUE TITLE
Swapping disk images

### ISSUE THREAD

**Issue by IanSimpsonNZ** [ivanizag/izapple2#19]
This is my favourite Apple ][ emulator, thanks for all the hard work.

Is it possible to change disk images while the emulator is running - to simulate swapping a floppy disk?  Sorry if this is obvious and I have missed something.

**Comment by ivanizag** [comment]
Thank you Ian. you made my day.

The emulator is lacking very basic features like a means to swap disks. The emulator supports it, but the interface does not.

I mostly write it as a means for me to study how the Apple II works and to improve on my Go understanding. I don't particularly enjoy or have good skills on UI development, that's why I'll probably never write that feature. I would love if somebody takes it from here and builds a nice interface.

**Comment by ivanizag** [comment]
Disk images can be changed on the last release by dropping files on the left or right half of the window.
